---
collections:
- name: community.general
  type: galaxy
- name: prometheus.prometheus
  type: galaxy
- name: devsec.hardening
  type: galaxy
- name: grafana.grafana
  type: galaxy
  version: 5.6.0

roles:
- name: hifis.unattended_upgrades
  version: "v3.2.1"
- name: fubarhouse.golang

