---
- name: Discover npm binaries directory
  shell: ". ~/.nvm/nvm.sh && nvm exec --silent default npm config get prefix"
  args:
    executable: /bin/bash
  register: npm_prefix
  changed_when: false

- name: Install global npm packages
  shell: ". ~/.nvm/nvm.sh && npm install -g rivalz-node-cli"
  args:
    executable: /bin/bash
    creates: "{{ npm_prefix.stdout }}/lib/node_modules/rivalz-node-cli/"
